export const actionTypes = {
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",

    ADD_PACK_TO_CART: "ADD_PACK_TO_CART",
    FETCH_PACKS: "FETCH_PACKS",
    PACKS_IS_LOADING: "PACKS_IS_LOADING",
    PACKS_FETCH_DATA_SUCCESS: "PACKS_FETCH_DATA_SUCCESS"
}

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";